### ISSUE TITLE
Status bar colour unchanged

### ISSUE THREAD

**Issue by ombrophile** [perragnar/dark-plus-tweaked#1]
First of all thank you for tweaking the dark theme as well. 

Although, from the screenshot, it seems that the status bar has a dark colour rather than the default purple colour, I am unable to see the change in my system. In my case, vscode status bar is rendered in the same purple colour as in the default theme. 

I would like to know whether the theme really changes the colour of the status bar to black. And if it does, then why is it not changing in my system?

**Comment by perragnar** [comment]
Hey! Are you using an addon that changes the status bar color, like the VIM extension?

**Comment by ombrophile** [comment]
No. I just have the "light+ tweaked" theme, "dark+ tweaked theme", and "python" extensions installed.

**Comment by perragnar** [comment]
It seems like the status bar is purple when I open VSCode without any files open and just the welcome tab. When I open some files or a project folder, the status bar turns dark. Is that the case for you as well?

**Comment by ombrophile** [comment]
In my case, when vscode opens without any files, the status bar is purple. Even when I open a file, the status bar stays purple. 
Only when I open a project folder does the status bar turns dark.

**Comment by ombrophile** [comment]
I was comparing the theme's json file with the json file of your "Light+ tweaked" theme. It seems that the property `statusBar.noFolderBackground` has not been set here. If I set the value as `"statusBar.noFolderBackground": "#252526"`, status bar colour changes to dark for the other cases as well.

**Comment by perragnar** [comment]
Alright, that fixed the issue. Thanks for finding it!
I've updated the package and published it to the marketplace.
